### ISSUE TITLE
NEW FEATURE REQUEST: WEBAPI status in json format

### ISSUE THREAD

**Issue by skizzo3000** [patience4711/read-APSystems-YC600-QS1-DS3#102]
@patience4711 i'm using you firmware, is very stable and useful to monitor inverter.
Is possible for you to make a web page in json format with all status of ECU and inverter ?
For example
http://ipecu/status_json

response

> HTTP/1.1 200 OK
Content-Length: xxxxx
Content-Type: application/json
Connection: close
Accept-Ranges: none

> {
	"ecu" : {
		"fw_ver" : "ESP-ECU_v9_8",
		"esp_chip_id": 12624536,
		"flash_chip_id" : 1458270,
		"ide_flash_size" : 4194304,
		"real"flash_size : 4194304,
		"free_mem" : 18584,
		"remote_ip": "192.168.123.2",
		"wifi_strengh" : -45,
		"zigbee_up" : 1,
		"unixtime" : 1681138786
		},
	"inverterData" : [
		{
			"inverter_n" : 1,
			"serialnr" : 703000660661,
			"id" : "0xFC33",
			"signal_strenght" : 23,
			"ac_v" : 232.1,
			"temp" : 33.5,
			"panels" : [
				{
					"panel_id" : 1,
					"vdc" : 34.3,
					"adc" : 10.4
				},
				{
					"panel_id" : 2,
					"vdc" : 31.7,
					"adc" : 12.4
				},
			]
		},
	]
}

Thanks
Sk3

**Comment by patience4711** [comment]
Not possible, i don't want to sacrifice program space for this.
