### ISSUE TITLE
Strange value in Domoticz

### ISSUE THREAD

**Issue by LordDarkneo** [patience4711/read-APSystems-YC600-QS1-DS3#110]
Hi there,
As evrything's working quite fine now on my installation, I just realized that sometimes, I have "wrong" values in my Domoticz sensor. It happens many times that I have a "negative" consumption. Example yesterday:

![image](https://user-images.githubusercontent.com/40838306/233823982-dc41d74a-37df-403f-84ff-ebe0eb8580a2.png)

Any idea on how to check why this value is stored / sent by the ESP?

Thanks for your help

**Comment by joffito** [comment]
This is domoticz behaviour, not the ESP ECU. You need to create a sensor Electric (Current + Counter) and use the values from the screenshot
![Uploading Screenshot_20230423_102320_Firefox.jpg…]()

**Comment by LordDarkneo** [comment]
Hi and thanks for your reply. 
I though it might be linked to a wrong data sent by the ESP... The only difference is the read value I set to "Computed".
![IMG_20230424_074822](https://user-images.githubusercontent.com/40838306/233916347-5882acb0-7b2f-41bc-b0dc-00d631bbcba3.jpg)
I do not really understand what's the difference between the 2 options (even reading the documentation).... Let's see if the behavior is still then.

**Comment by joffito** [comment]
someone explained that behaviour in another issue. i think when you set to 'from device' then domotic sees a 0 value on ecu reset and then subtracts your current generation from 0 (as to calculate the difference between readings) leading to a negative value.
