### ISSUE TITLE
APSystems DS3-M verified

### ISSUE THREAD

**Issue by tomorrowflow** [patience4711/read-APSystems-YC600-QS1-DS3#113]
Hi,

just to let you know, I successfully set up three inverters. Two DS3-M (800 Watt output) and one DS3-S. All three are providing data as expected via an ESP8266 and your application.

Thank you @patience4711 for your hard work, I am happy to finally see the data via MQTT in my OpenHAB setup.

Florian

**Comment by patience4711** [comment]
@tomorrowflow   thanks for sharing this.
