### ISSUE TITLE
feature request: turn off / turn on (export limit)

### ISSUE THREAD

**Issue by kiss81** [patience4711/read-APSystems-YC600-QS1-DS3#118]
Not sure if this is possible, but some inverters support a temporary export limit. (turn off the inverter)
Is there any chance this could work? In the Netherlands we sometimes have negative prices an hour a day so you have to pay for producing electricity. 
I am using this on a qs1 by the way.

**Comment by patience4711** [comment]
@kiss81  It should be possible if we knew the zigbee commands for it. Sadly we don't. Someone with an official ECU can provide this data with a zigbee sniffer, so far no volunteer has come forward.

**Comment by kiss81** [comment]
I asked on a forum that's working on integration of the official ecu. I do hope one has a sniffer...
