### ISSUE TITLE
Add MQTT output format for ThingSpeak.com

### ISSUE THREAD

**Issue by juliend20** [patience4711/read-APSystems-YC600-QS1-DS3#119]
I'd like to send data to ThingSpeak. We can send to thingspeak over mqtt. He needs to create a new devices on the platform with credentials.

We need to change format of topic/payload:

https://fr.mathworks.com/help/thingspeak/publishtoachannelfeed.html

By example :

Topic: channels/33301/publish
Payload: field1={power1}&field2={power2}&field3={energy1}&field4={energy2}&field5={temp}&status=MQTTPUBLISH

We need to add a new field to define "Client ID". Because we already have a Username, Password. 

If you want I can do these changes. You only need to give me access to create a Pull request I think.

Thanks you so much for your work. It's work just perfect.

**Comment by juliend20** [comment]
Thank you for your answer. 

I agreed with the payload format. No matter of energy per panel. 

But I need to set on frontend the clientId with the deviceId from thingspeak (generated). Otherwise it doesn't work.

The esp id can't be define. It's mac adress I think.

OK I'll try to open a pr tomorrow.

**Comment by juliend20** [comment]
Hi, at first I change your code in local. But I don't know how I can "build" the firmware. Please tell me what I need to do. Thank you

**Comment by juliend20** [comment]
@patience4711 The clientId for mqtt is needed for thingspeak see documentation https://fr.mathworks.com/help/thingspeak/publishtoachannelfeed.html

Name: MyChanName
Client ID: ENTER_MQTT_DEVICE_CLIENT_ID
Host: mqtt://    mqtt3.thingspeak.com
Port: 1883
Username: ENTER_MQTT_DEVICE_USERNAME
Password: ENTER_MQTT_DEVICE_PASSWORD
Clean Session: true

I made the test with an MQTT client. If I don't set the client ID Thingspeak refused to write data in the channel.

I made changes on your code to support mqtt for thingspeak.  How can build your firmware please?

**Comment by patience4711** [comment]
Yes i know that all, but how can you make the esp connect to mqtt3.thingspeak.com ?

Like so :  MQTT_Client.connect( clientid, Username, Password ) ?

**Comment by juliend20** [comment]
> Ad explained in the readme, i don't support the compiling of the program. If you want to know how to compile an arduino sketch there is enough to be found on the internet.

I understand that. But I'm sorry to hear that. Because I'm not a beginner on Arduino. I don't need a full tutorial to build your code. Just tell me if you use Arduino ide or cmd line.
