### ISSUE TITLE
Wifi credentials not saved

### ISSUE THREAD

**Issue by rvakkeren** [patience4711/read-APSystems-YC600-QS1-DS3#123]
I've uploaded the bin file to an esp8266. I can connect to the AP (ECU-xxxx) and after filling in my wifi-credentials, the ESP shows 3 flashing light and reboots. Somehow, it doesnt store the credentials and falls back the AP mode again.

Any ideas on this?

**Comment by patience4712** [comment]
[read here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/issues/115)
