### ISSUE TITLE
Wiki updated needed for requesting data via HTTP

### ISSUE THREAD

**Issue by hvdb** [patience4711/read-APSystems-YC600-QS1-DS3#128]
Hello,

I am using the endpoint in my home assistant, so needed to update them as they where changed :)
The wiki is not updated yet: https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/wiki/08-MISCELLANEOUS#request-data-via-http

Proposal:

When you issue a link like http://ip_of_esp_ecu/get.Inverter?inv=0, you get all data from inv0 in a json with the format: 

```json
{
  "inv": 0,
  "name": "fietsen",
  "polled": true,
  "type": 2,
  "serial": "904000148912",
  "sid": "6FFF",
  "freq": 50,
  "temp": 14,
  "acv": 233.4,
  "sq": 46.7,
  "pw_total": 27.5,
  "en_total": 0.04,
  "dcv": [
    36.4,
    32.4,
    "n/e",
    "n/e"
  ],
  "dcc": [
    0.5,
    0.8,
    "n/e",
    "n/e"
  ],
  "pow": [
    11.2,
    16.3,
    "n/e",
    "n/e"
  ],
  "en": [
    16.52,
    24.06,
    "n/e",
    "n/e"
  ]
}
```

The numeric values are float, all panels are available in the array provided.

**Comment by patience4711** [comment]
@hvdb  Done, thanks for your input.
