### ISSUE TITLE
Can an inverter be used with this solution if it was previously paired with an ECU

### ISSUE THREAD

**Issue by kaneda-fr** [patience4711/read-APSystems-YC600-QS1-DS3#130]
Hi,

I'd like to use an ECU to update the inverter firmware.

Do you know if it's then possible to go pair them again with my ESP8266 to track usage ?

Many Thanks

**Comment by joffito** [comment]
it worked for me and an ECU B which i had paired with my inverter for about two weeks.

**Comment by kaneda-fr** [comment]
Great,
Thanks a lot for your response, I have a good deal on one and will try it out.
