### ISSUE TITLE
Visiting the menu from outside own network

### ISSUE THREAD

**Issue by baba2k** [patience4711/read-APSystems-YC600-QS1-DS3#132]
Hi,

> secured the system, prevent visiting the menu from outside own network

is it activated by default? Is is it possible to disable this setting in webpage? I have multiple vlans in different subnets and cant reach the device after update.

Thanks!

**Comment by patience4711** [comment]
please read [here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/wiki/08-MISCELLANEOUS#security)
