### ISSUE TITLE
Configurable ECU ID via webinterface

### ISSUE THREAD

**Issue by baba2k** [patience4711/read-APSystems-YC600-QS1-DS3#133]
Hi!
Is it possible to make https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/0ea4bc5cc201c80e055f6fd30e59f6a2284e74c1/ESP-ECU-v10_8.ino#L184 ECU_ID configurable via webinterface? So I could set the ECU ID of my ECU-B and use both devices at same time. I want to use ECU-B for Firmwareupdates and 10y ears warranty.

Thank you!

**Comment by baba2k** [comment]
it is already configurable... sorry

**Comment by sebastianrothe** [comment]
See #141
