### ISSUE TITLE
Error adding the ninth inverter

### ISSUE THREAD

**Issue by pdufrenne** [patience4711/read-APSystems-YC600-QS1-DS3#144]
High,

I appreciate the effort you put into this software.
However, I encountered a problem when added the ninth inverter. (I have exactly nine inverters)
The Add button and all other options are gone.
See the picture.

<img width="1238" alt="Scherm­afbeelding 2024-07-30 om 15 41 54" src="https://github.com/user-attachments/assets/ac91bf31-64f6-4dbf-b738-b4d9d17811b3">

I use a Wemos D1 Mini and a CC2530 Zigbee module

Thanks in advance,

Peter

**Comment by patience4711** [comment]
Hi Peter, i remember we had this problem with the esp32 version, that was a problem in the html of the inverterpage. 
So i made some changes in the html and compiled a new version.  Find it [here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU-v10_9a.bin). Sadly i have no means of testing so i cannot guarantee that it will work.
If it doesn't work i would like to suggest that you buy an ESP32 which would probably work better with 9 inverters.. Please look [here](https://github.com/patience4711/ESP32-read-APS-inverters)

**Comment by patience4711** [comment]
No thanks, you're welcome
