### ISSUE TITLE
Zero injection 

### ISSUE THREAD

**Issue by JMMarquezL** [patience4711/read-APSystems-YC600-QS1-DS3#145]
I'm specifically interested in whether it's feasible to control the microinverter's zero injection mode via the ESP ECU. Thanks.

**Comment by patience4711** [comment]
If you know the zigbee command it would be doable via the console. Sadly i don't know the command.

**Comment by JMMarquezL** [comment]
How can I acquire the command? What was your method for decoding the Zigbee data? Thank you very much.

**Comment by patience4711** [comment]
This question has been asked before.
read [here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/issues/118) and
to get an idea how the reversed-engineering went, read [here](https://github.com/Koenkk/zigbee2mqtt)

In short: Someone with an official ECU needs to sniff the communication ecu<->inverter.
