### ISSUE TITLE
In v9 no Data on panel 3/4

### ISSUE THREAD

**Issue by PLCHome** [patience4711/read-APSystems-YC600-QS1-DS3#25]
Since v9 there is no data for the panel 3/4 on QS1 for current and volt.
The powervalues works for panel 3/4

![image](https://user-images.githubusercontent.com/29116097/164406864-46ca4a0b-a443-4158-ac09-2aad89872557.png)

**Comment by patience4711** [comment]
@PLCHome  repaired in version 9_2

**Comment by PLCHome** [comment]
you are great
tested
works for me
