### ISSUE TITLE
Problem with my CC2531 USB stick does anyone have an idea

### ISSUE THREAD

**Issue by redseasix** [patience4711/read-APSystems-YC600-QS1-DS3#26]
Hello all,

I am not sure if the CC2531 works properly at all.
I have written the firmware: **CC2531ZNP-with-SBL.hex** from the ZIP file to the USB stick with the Flash Tool from TI. The verification within the TI tool said OK.
When poking the LED lights up for a while then it goes off on the stick and comes on after a while.
Now I am in the console and have there: 10;ZBT=2710AABBCC entered and as a response this received: 
![console-1](https://user-images.githubusercontent.com/14967083/164439596-6350c311-3c08-48f0-ba62-2925a5a29e95.jpg)
Does that mean that the stick was recognized correctly? Or should there be something after answer?
Do I understand correctly "starting ZB coordinator failed" that means that it is not properly there.
I use this CC2531-USB stick:
Does that mean that the stick was recognized correctly? Or should there be something after answer?
Do I understand correctly "starting ZB coordinator failed" that means that it is not properly there.
I use this CC2531-USB stick:

![zigbee USB Stick](https://user-images.githubusercontent.com/14967083/164442067-24f64a85-c009-41de-a97f-b47f2127ee0c.jpg)

Here is my wiring

ESP         ZIGBEE USB STICK
GND    ->   PIN 1 GND
3,3 V    ->   PIN 2 VDD
D8        ->  PIN 3 Debug Clock
D7         -> PIN 4 Debug Data
D5         -> PIN 7 Reset

flat cable are 1:1

![esp2866-1](https://user-images.githubusercontent.com/14967083/164441641-da0ee4a9-e64a-4805-8184-eca0bbcc9688.jpeg)

![esp2866-2](https://user-images.githubusercontent.com/14967083/164441673-6cce6858-7478-46a4-8f92-ae2beb25ce7a.jpeg)

I also flashed a 2nd USB stick and got the same result.

could you please give me a hint, where I can look further, what I am doing wrong?

Thank you redseasix

**Comment by patience4711** [comment]
@redseasix  you are not getting reponse so either the device or the serial communication doesn't work. You could try to exchange rx and tx

**Comment by SteffenB71** [comment]
Hallo
cc2531 -> esp (nicht von mir getestet!)
P0.1 -> d8
P0.3 -> d7
Rst-> d5
vcc -> 3,3 V - 2
gnd -> 1
The CC2531 is treated like the CC2530. The firmware that is flashed can also be from CC2530.
Steffen

**Comment by redseasix** [comment]
Hello Owner patience4711

Thanks for your feedback. your hint put me on the right track and the Zgbee stitch now answers correctly to 10;ZBT=2710AABBCC.

What did I do:

Programmed Zigbee firmware CC2530ZNP-with-SBL.hex from the folder CC25xxfirmware ds3 to my Zigbeestick CC2531.
now it responds correctly

cc2531 -> esp
P0.2     -> d8
P0.3     -> d7
Rst       -> d5
vcc       -> 3,3 V
gnd      -> GND

IO Connector of Zigbee Stick:
![IO Connector](https://user-images.githubusercontent.com/14967083/165292053-e3455d02-3b8a-43ae-b421-60c555f1094f.jpg)

![IO-Connectotr-1](https://user-images.githubusercontent.com/14967083/165292699-5c6a6d7a-6285-4ae0-9416-1305343cc3b3.jpg)


here is my working wiring

![verderahtung](https://user-images.githubusercontent.com/14967083/165292412-9007dae9-5e33-4154-8458-d766779fc1d4.jpeg)

now it's time for the next steps

**Comment by redseasix** [comment]
super that was the starting signal for me. The Zigbee stick responds exactly as described.

now I have to look that I get the ESP with the CC2531 stick close to my two QS1. (Gatenhaus about 80m away (Bad WLAN with -81dBm So I have to build me another WLAN repeater.

in 3 weeks comes another DS3 which is already here with 2 solar cells a 200 watts to the start.

please adapt in the README.md still the allocation for the CC2531 Zigbee stick:

**cc2531 -> esp**
P0.2 -> d8
P0.3 -> d7
RST - > d5
VCC -> 3.3 V
GND -> GND

Thanks for the help
