### ISSUE TITLE
Can't add inverter

### ISSUE THREAD

**Issue by StiffelMS** [patience4711/read-APSystems-YC600-QS1-DS3#30]
Hi everyone!

I just received my nodeMCU and CC2530, Flashed "ESP-ECU_v9_3" and "CC2530ZNP-with-SBL.hex" for reading out my APSystems QS1.

In webinterface, I can't save/pair any inverter. Is the "pair-button" the "save-button" in the button right corner?
Every time I fill out the inverter-add-page and click save, the nodeMCU reboots...

Any ideas? Thanks!

**Comment by StiffelMS** [comment]
I flashed nodeMCU again, now it saves data. 

What is the username and password (the pw must be 1111 (standard) right?)? I can't log in...

**Comment by pixeldoc2000** [comment]
@StiffelMS 
I believe it is user: "admin" and password: "1234" by default ?

**Comment by patience4711** [comment]
@StiffelMS  It is 0000 you should have seen that in the wifi configuration access point.

**Comment by patience4711** [comment]
@StiffelMS its 'admin'and 0000 or 'user' and 1111 but the user cannot change settings.

**Comment by StiffelMS** [comment]
thx
