### ISSUE TITLE
polling via MQTT "automatic, skipping"; failed?

### ISSUE THREAD

**Issue by mamaretti** [patience4711/read-APSystems-YC600-QS1-DS3#33]
hi patience,

when i send a cmd with {"poll":0} I get "automatic, skipping"

als when I use the URL-Parameter  http://IP/POLL=0

it seams that no poll ist triggered then. is that right ?

thx

**Comment by patience4711** [comment]
@mamaretti  yes, this is explained in the readMe.txt in the download package. And in the help menu of the settings.

**Comment by mamaretti** [comment]
sorry I don't understand

`The automatic polling can be disabled. This allows the user to issue a mosquitto message to the in-topic, e.g. {"poll":0}. 
We can also use an api to force polling e.g. http://ip_of_ecu/POLL=0
This way we can let our domotica programs ask the ecu for data. For security reasons the api works only from inside your network.`

when I di this I get no new data from inverter.

when I do 10;POLL=0 via console I get data from inverter.

**Comment by patience4711** [comment]
@mamaretti  
> when I di this I get no new data from inverter.
What exactly did you do? And what did you get?

**Comment by mamaretti** [comment]
when I do a poll CMD in console "10;POLL=0" I get this
<img width="464" alt="Bildschirmfoto 2022-05-18 um 14 36 42" src="https://user-images.githubusercontent.com/3448514/169040619-703badff-b430-4218-aaa7-aa1a0576c1c5.png">

when I do a poll via MQT (JSON "{"poll":0}" to /cmd) I get this in console an no new inverter values
<img width="416" alt="Bildschirmfoto 2022-05-18 um 14 37 07" src="https://user-images.githubusercontent.com/3448514/169040966-8314f722-97bc-445c-8e4c-e831665cc36f.png">

when I do I browser command http://IP/POLL=0 I get "automatic polling, skipping" message in browser, no new values, no message in console.

tried different browsers

im still on version 8.
is that the problem?

**Comment by mamaretti** [comment]
ahh, i see.
thx and sorry for asking
