### ISSUE TITLE
DS3 Inverter temperature at night

### ISSUE THREAD

**Issue by karlheinz2000** [patience4711/read-APSystems-YC600-QS1-DS3#37]
Reported temperature via MQTT at startup in the morning and shutdown at night is not consistent.
At shutdown temperature is reported as 0°C, which is not correct. At midnight last valid temp from evening before is sent, followed by 0°C again. At startup in the morning same: last temp from evening followed by 0°C. 
After that temperature is valid.

2022-05-30_20:52:31 15.4
2022-05-30_20:57:29 15.0
2022-05-30_21:16:35 15.0
2022-05-30_21:16:35 000.0
2022-05-31_00:00:02 15.0
2022-05-31_00:00:02 000.0
2022-05-31_05:24:56 15.0
2022-05-31_05:24:56 000.0
2022-05-31_05:37:30 5.1

 
![2022-06-01_21h53_02](https://user-images.githubusercontent.com/11009766/171490092-d8bf131d-505d-4dc1-80d2-30d6e386ed95.png)

SW: esp-ecu-v9_4

**Comment by patience4711** [comment]
@karlheinz2000  thats true, at sleep and in the morning there are no measured temperature values, so the mqtt values are always wrong. That is why they are set to 0. In fact the best thing to do is not send any temperature values at all when there is no polling. But we want all the other values set to 0 for our graphs, thats why there is a mqtt message at midnight and at wake-up.  Maybe we can retain the last measured temperature untill new values are polled.  Anyway whatever solution we choose, it is always incorrect. 
I'l think it over..

**Comment by patience4711** [comment]
@karlheinz2000 
The only thing that i can imagine is that there is another 'ghost' inverter that sends 0 values at these times.

Could you look at the infopage for the variable inverterCount. This value should reflect the amount of inverters. Also the filesystem contents should show  one Inv_Propx.str per inverter.

If there seems nothing wrong, would it be possible to read the mqtt transmission at midnight on your RPI? Jou only have to type<br> 

**mosquitto_sub -d -t yourtopic** into your ssh terminal (you probably knew this already)

**Comment by karlheinz2000** [comment]
@patience4711 
Yes, it was because of two inverters. The old inverter from power measurements was still added, but not paired. After deleting this inverter temperature reporting is much cleaner. 
Now still 2 points do not look nice, but is is not an issue for me.
1) at midnight, the last temperatue from evening is sent again.
2) at wake up in the morning, the last temperatue from evening is sent again.
