### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by emuell36** [patience4711/read-APSystems-YC600-QS1-DS3#40]
Hey,

do you plan do port this to the ESP32 as well?
For me the ESP8266 feels a bit outdated which is why there are just ESP32's flyn around here :)
If not I will just order an NodeMCU

Regards

**Comment by patience4711** [comment]
Sorry but no, the esp12 is good enough for this task.

**Comment by emuell36** [comment]
Thanks for clarification...was more due to (personal) availability....I had a bunch of ESP32 flying aroung but no esp12 :/
