### ISSUE TITLE
DS3H compatibility. (Has anyone checked it ?

### ISSUE THREAD

**Issue by ortegafernando** [patience4711/read-APSystems-YC600-QS1-DS3#41]
Hi, thanks a lot for your great job

I haven't still buy anything but I need DS3H 960w models. I don't want an EC from apsystems. 

Has anyone this working with DS3H model ?

I can't see any way to open a discussion, so I have open an issue despite it is not an issue. 

Does anybody know the answer? 

Thanks.

**Comment by patience4711** [comment]
Hi, i don't know the answer but i expect that it will work, cant see why not. I think you can take the risk, there is no big capital involved.
Good luck and please report back your experiences.
