### ISSUE TITLE
Firmware CC2531 DS3 Serie

### ISSUE THREAD

**Issue by smoki3** [patience4711/read-APSystems-YC600-QS1-DS3#45]
Hi,

on the lastet release the following firmware files for the DS3 is included:

![image](https://user-images.githubusercontent.com/9723729/186408013-b8a58482-0d17-4a09-b9c0-fbd406e61d04.png)

Which is the correct one if I am using a CC2531 USB Stick?

In the YC-QS folder I see a dedicated file for the CC2531

**Comment by patience4711** [comment]
CC2530. From the wiki: 
>It seems that for the cc2531 the firmware for the cc2530 will work
