### ISSUE TITLE
get this working on a CC2531USB-RD

### ISSUE THREAD

**Issue by JochenKlenk** [patience4711/read-APSystems-YC600-QS1-DS3#48]
Hi guys,
I have an CC2531USB-RD lying arround here and try to understand if we can get this working directly on that device hugged up to an RPi with Homeassitant running on it.

Thanks for inputs.

**Comment by Hansiart2** [comment]
Its not completely clear to me what exactly you want. If you installed the rpi-ecu you can also install Homeassistant i think. The stick will work but not via usb.
