### ISSUE TITLE
Polling via MQTT does not work?

### ISSUE THREAD

**Issue by elektrinis** [patience4711/read-APSystems-YC600-QS1-DS3#50]
Sent from another device:
`{"poll":0}`

Received in console:
`mqtt received {"poll": 4}`
`polling = automatic, skipping`
`mqtt received {"poll": 0}`
`polling = automatic, skipping`

But then nothing happens.

Also in there a command to poll all inverters at once?`

Also MQTT does not work with uppercase POLL, as provided in the manual:
`{"POLL":0}`

**Comment by Hansiart2** [comment]
Correct, this does only work when automatic polling is disabled.  No such command but why not. I' look at it over 2 weeks, now on holidays

**Comment by patience4711** [comment]
I assume that if you have seen the instructions in the wiki, you should have seen that the autopolling should be disabled to make this work. I changed the uppercase POLL to poll.

**Comment by patience4711** [comment]
Here is a unofficial 9_5 version [esp-ecu-v9_5_BETA](https://1drv.ms/u/s!AkMG5FvUwhedi3bBwwrSfOdlptlS?e=FuWs4L)

Could you install it and check if it works as desired.

**Comment by elektrinis** [comment]
Will check it next week maybe, bit overwhelmed with work now.
Thank you!
