### ISSUE TITLE
Documentation : clarification

### ISSUE THREAD

**Issue by silbor** [patience4711/read-APSystems-YC600-QS1-DS3#64]
Suggestion : clarify description of firmware update on https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/wiki/8-MISCELLANEOUS
```
The update function only updates the ECU on the ESP, NOT the CC2530 firmware. 

In order to update or change the firmware of the bluetooth module, you will need to
rewire the ESP-CC2530 to flash mode, flash the CCLoader firmware on the ESP, then 
use CCloader to update/change the CC2530 firmware, rewire for operation mode, and
flash ESP-ECU again
```

**Comment by patience4711** [comment]
bluetooth?

**Comment by silbor** [comment]
sorry zigbee of course

**Comment by patience4711** [comment]
I think that it is clear to most of the users that the ota only updates the esp software. For the zigbee module it is already written how to put firmware on it, so thanks but i don't see this as an addition.
