### ISSUE TITLE
Support for Ap Systems YC500i

### ISSUE THREAD

**Issue by gerardwr** [patience4711/read-APSystems-YC600-QS1-DS3#68]
Hi,

Job well done!

Is this software also suitable for the older YC500i?

Regards,
Gerard.

**Comment by patience4711** [comment]
Hi Gerard. Sorry but no.

**Comment by gerardwr** [comment]
That’s too bad. Does this mean that the YC500i has a different Zigbee protocol, or that it does not use Zigbee at all?

**Comment by patience4711** [comment]
You tell me, you own one, i don't.

**Comment by gerardwr** [comment]
Yep, own one since yesterday!. No clear info found on Google, So I hoped you could give me a head start. Let’s see what I can find out. Thanks for your reaction.

**Comment by gerardwr** [comment]
Found some more info on the YC500. It seems that the data from the inverter is sent by pulses on the 220V power line. So no Zigbee communication on the YC500.

Some technical info here:

[https://sites.google.com/site/ecu2pvo/aps-aflc](url)
