### ISSUE TITLE
How to set MQTT format?

### ISSUE THREAD

**Issue by 1Joe1** [patience4711/read-APSystems-YC600-QS1-DS3#69]
Hello, 

I read about the 4 different MQTT formats available, but can not find any hint on to to set the format.

Can anyone help?

**Comment by babajun12** [comment]
Just have a look into -menue-mosquitto - select format

**Comment by 1Joe1** [comment]
I didn't have the option there.
![Screenshot_2022-11-25-13-03-49-618_com android chrome~2](https://user-images.githubusercontent.com/43110637/204021594-780caa4a-453d-469a-92ac-12ae54bd1839.jpg)

But knowing that it should be there helped me to figure out this was due to my version. In version 9.4 there was no such option.

Thanks for helping!
