### ISSUE TITLE
Wrong sunrise and sunset time

### ISSUE THREAD

**Issue by 1Joe1** [patience4711/read-APSystems-YC600-QS1-DS3#70]
![Screenshot_2022-11-24-17-57-09-207_com android chrome~3](https://user-images.githubusercontent.com/43110637/203836770-16cd0191-e6b7-4718-954e-4d558adccc91.jpg)
These are my geographical settings. I am located in Germany and postive to have the correct coordinates. The resulting time is correct, but the sunset and sunrise times are off by a few hours. Any ideas on what I might be doing wrong? Am I missing any other relevant settings?
Are there any known issues?

**Comment by frtz13** [comment]
you mixed up longitude and latitude.

**Comment by 1Joe1** [comment]
Thank you so much! Should have seen that myself.
