### ISSUE TITLE
STL - Lid needs to be "inverted" upside down

### ISSUE THREAD

**Issue by LordDarkneo** [patience4711/read-APSystems-YC600-QS1-DS3#75]
Hi there,
I am starting my journey on this projet, and started by 3Dprinting the STL provided. The lid part is inverted:
![image](https://user-images.githubusercontent.com/40838306/212022513-fb3b1af8-c83a-4e0c-8e70-a94749f09154.png)

Thus in order to have it closing properly, I mirrored it upside down in my slicer (or in 3DBuilder):
![image](https://user-images.githubusercontent.com/40838306/212022869-1a9e8460-6256-4eee-bdb9-5cbb1de51858.png)

That's not that difficult for someone familiar with 3DPrinting, but maybe you can modify the provided STL, so it can be printed without any modification?
Cheers

**Comment by patience4711** [comment]
I corrected this, thanks for pointing it out.
