### ISSUE TITLE
Add userconfig in webui for ntp timeserver

### ISSUE THREAD

**Issue by smartboart** [patience4711/read-APSystems-YC600-QS1-DS3#76]
Hello, it would be nice to have a possibility to change timeserver address / local ip adress, for those who wont have the device online in the internet...
Best regards

**Comment by patience4711** [comment]
Yes.

**Comment by smartboart** [comment]
Hello ...can change the ip Adress by myself for the ntp Server.. Compiling is not pissible without Changing some big to snall Letters / Endings...compileeror...the exportet bin file is then not working...why is it not pissible to compile the Master Branch without errors?
