### ISSUE TITLE
How to reset the admin password

### ISSUE THREAD

**Issue by LordDarkneo** [patience4711/read-APSystems-YC600-QS1-DS3#78]
Hello There,

I was following the wiki to change the "user" account password in the Settings tab... But unfortunately it seems to have changed the admin password also...

After saving, I have been requested the login page below
![image](https://user-images.githubusercontent.com/40838306/213764707-efa49401-14d0-4c8a-a007-56a28f8f2d8f.png)
And I cannot connect using admin pwd 123456789... I tried to keep admin with the password I set up, still not working... Even user (instead of admin) is not working with both passwords...

I tried to reflash the nodemcu, but it did reset the configuration (I still have the same message).

How to reset the admin password? 

Thanks for your help!

**Comment by patience4711** [comment]
The admin password is set in the accesspoint for security reasons. Via the menu you can start the AP.

**Comment by LordDarkneo** [comment]
> The admin password is set in the accesspoint for security reasons. Via the menu you can start the AP.
The problem I am facing is that I cannot access the access point no more. 
I tried to connect D4 and ground, but it doesnt drop the wifi configuration (the board keeps booting normally). I tried to flash the board using a blank firmware and reflashing with the ESP-ECU, but the config is still.... And I cannot access the menu no more because of the admin login console...

**Comment by joffito** [comment]
power cycle the esp and then hold the flash button for a while. it'll reset it (or at least the wifi settings).

**Comment by LordDarkneo** [comment]
Thanks, that did the trick! Press the Flash button, the led lights up. Keep it pressed until the led is off and release the flash button.

The "root" issue was my password too long.... it was truncated in the interface (you see the limitation to 10 digits only when the field is empty... Could be good to write it in the documentation as a warning, no?)
Thanks a lot for your support. Waiting a bit of sun to try this on my DS3L :)
