### ISSUE TITLE
EcuESP reports negative energy values

### ISSUE THREAD

**Issue by joffito** [patience4711/read-APSystems-YC600-QS1-DS3#85]
I observe that during midnight my Domoticz on my RPI seems to receive a negative energy value from the ECU ESP.
Unfortunately i do not have more data to show because i set it up from scratch yesterday but i observed this phenomenon since more days.

I set up my domoticz device as Electric (Instant + Counter) with the values from the picture.
I think somehow during reset of the daily Energy generated the ECU ESP seems to send a negative value over MQTT.
This value is close the the energy generated during that day i think.

Can someone confirm this ?

![img3](https://user-images.githubusercontent.com/114950821/217789256-34326d59-b953-42d0-a15f-f0fccc2f13b1.jpg)

![img1](https://user-images.githubusercontent.com/114950821/217789244-77a1b3e0-45da-4e33-a89f-a9c69afc4c71.jpg)

**Comment by bwbboot** [comment]
I have this same issue. At first i thought this was ESP ECU related but I see the same behaviour using the latest RPI ECU.

**Comment by bwbboot** [comment]
It seems that using the option energy "read from device" in Domoticz is a total counter and calculates the daily delta. However the values from ECU are reset daily causing the negative value. I did some testing and changing to "Computed" solves the issue. 

@patience4711  is there an option to keep increasing the counter without a daily reset?

**Comment by joffito** [comment]
you're right, thanks!
this is domoticz behaviour. i changed to computed and the issue is gone.
closing the issue now.
