### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by patience4711** [patience4711/read-APSystems-YC600-QS1-DS3#89]
In the current version (v9_6) we can see inverteroutput of only one inverter that we selected in the frontpage. I developed a webpage that shows data from all inverters at once. Please see the picture below to get an idea. 

Since i have no working ESP-ECU i can only test in a artificial environment, and that seems to work.  I would appreciate it very much if someone is willing to install this and give feedback. I am especially interested in users who have more than 3 inverters and have used version 9_6 without any problem.

![frontpage](https://user-images.githubusercontent.com/12282915/220932986-e8d972de-cfcc-4211-8714-8077d6f1e80f.jpg)

**Comment by swbouman** [comment]
Next week, there should be 13 panels installed with 7 ds3 inverters. I’ll install this bin and test for you.

**Comment by patience4711** [comment]
@swbouman  Great, thanks in advance.

**Comment by Superbert25** [comment]
Hi,
I have installed this experimental version. I'm using 5 DS3L inverters with each 2 panels connected.

The version works fine upto now, I just noticed some strange behaviour in the build-up of the overview:

After initial access, only inverter 0 and inverter 1 are shown immediately:
<img width="868" alt="Initial home screen" src="https://user-images.githubusercontent.com/94918025/221422097-fda660de-49d1-4e2c-9f61-8770d1aacd92.png">

After a couple of appprox 15 seconds, the table is completed:
<img width="880" alt="after some time" src="https://user-images.githubusercontent.com/94918025/221422106-b631e348-52e5-4577-8eb1-d786b0dfc11a.png">

Thanks for your effort in developing this solution!

R.

Eeg.

**Comment by Superbert25** [comment]
My second screen-shot was from yesterday evening (inverters not yet paired), this one is from today:
<img width="909" alt="home screen after couple seconds" src="https://user-images.githubusercontent.com/94918025/221422346-8f8db24a-9157-49fb-92f5-95e49d75b779.png">

**Comment by patience4711** [comment]
@Superbert25 Thanks for your feedback, i solved that issue already. I think it looks good. Could you tell me how it looks on a smartphone?

**Comment by Superbert25** [comment]
Sure! Screenshot from iPhone 13:

![ESP-ECU](https://user-images.githubusercontent.com/94918025/221635412-b53929cf-0835-4573-b011-65024c22c35f.png)

It looks fine to me :-)

R.  Eeg

**Comment by patience4711** [comment]
Oke thanks, could you do this when there are values, preferably at the end of a shiny day, that will give me an idea.

**Comment by Superbert25** [comment]
Would be good to truncate the amount of digits in the total. The amount of digits causes the table to shift outside the screen width (iPhone 13):

![A2C8C492-2C66-450E-8237-6A9663B1DD01_1_201_a](https://user-images.githubusercontent.com/94918025/221816820-90650de4-ad69-4c08-bdb7-4e52370a01be.jpeg)

Based upon this screen-shot: If you truncate / round to 2 digits, I expect the table to fit the iPhone screen (even if total > 10 kWh total).

R.

Eeg.

**Comment by patience4711** [comment]
I changed the format of the total energy value to 2 decimal digits. Here is the latest version 
[ESP-ECU-9_7_beta](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_7_beta.bin)
 that also includes a feature to send mqtt output to a dedicated topic per inverter.

**Comment by Superbert25** [comment]
I am now using the second 9.6 experimental version. Couple of times a day the Zigbee Coordinator is restarted, sometimes the system as a whole is rebooted. I noticed that it seems related to loosing communication with one or more inverters.

I will build a new setup in a couple of weeks time with a longe range zigbee module (with PA and external antenna, that might improve things. I can share my findings here if you like.

**Comment by Superbert25** [comment]
Just installed the 9.7 beta:
- Issue of showing only 2 inverters at accessing the home screen is back in again
- Total is not limited to 2 digits
- 2 Reboots shortly after each other after installation

<img width="605" alt="9 7 beta - 2 digits" src="https://user-images.githubusercontent.com/94918025/222461707-d9116943-96b1-4105-a2c0-6b931fd27f10.png">


<img width="868" alt="Initial home screen" src="https://user-images.githubusercontent.com/94918025/222461979-39234d82-fdd9-420a-9428-7bf42ec19419.png">

**Comment by Superbert25** [comment]
> I am now using the second 9.6 experimental version. Couple of times a day the Zigbee Coordinator is restarted, sometimes the system as a whole is rebooted. I noticed that it seems related to loosing communication with one or more inverters.
> 
> I will build a new setup in a couple of weeks time with a longe range zigbee module (with PA and external antenna, that might improve things. I can share my findings here if you like.

My bad! I was actually using ESP-ECU_v9_7_exp_exp.ino.nodemcu.

Now reverting back to this experimental release as the beta is having some issues.

**Comment by patience4711** [comment]
This is all a little confusing, what i am trying to find out is if the version [9_6b](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_6b.bin) is working stable and the [9_7_beta](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_7_beta.bin) is not stable in your situation.  Otherwise i have no clou where to find the pain in the program. These are freshly compiled files, the 9_6b is 9_6 with the mqtt topic feature. The 9_7_beta has above that the new frontpage. 

Indeed,  the cc25xx crashes when there is bad communication with an inverter, this happens a lot when a high poll frequency is used. When the esp itself crashes than it could be a watchdogtimer issue.

**Comment by Superbert25** [comment]
I will install 9_6b now, but can only say tomorrow if that version is working fine (for me). If time permits, I will try 9_7_beta in the afternoon (next week I'm not able to perform any testing, so could be that you won't get any feedback from me until the week thereafter).

R.

Eeg.

**Comment by frtz13** [comment]
I installed the 9_7_beta an hour ago. until now, everything works as expected. I will report back tomorrow evening.

**Comment by patience4711** [comment]
@frtz13 Good to hear that. It would be helpfull if you could tell us in your next report:
- what CC25xx you use? 
- How many inverters/type you have
- do you experience crashes of the esp or the cc25xx
- does the energy total have 2 decimal digits? Frontpage on smartphone oke?

**Comment by swbouman** [comment]
can anyone help in understanding the output values? I assume the power value is the current power in Watt per panel, but when I multiply dcv*dcc the math has a different answer. How do I have to interpret the power and energy value?

                    dcv. dcc.  pow(w) energy
    "ch0": [ 32.2, 9.6,     274.7,   579.11]

The system is still crashing with 7 inverters polled. Ver (9.6b) 

I use a CC2530 + 2591
7 inverters ds3
And the totals look fine, but have a lot of digits sometimes.

**Comment by patience4711** [comment]
When i downloaded and installed version 9_6b  a minute ago i get this frontpage. You?
![front](https://user-images.githubusercontent.com/12282915/222735162-72b6415e-886f-42db-b4bb-460a16215698.jpg)

Power is calculated as follows ( (energy poll x+1) - energy poll x) ) / 300 sec )  So power is the avarage power between 2 polls. It is obvious that you can't use the u*i formula since these are momentary values that fluctuate a lot within 5 minutes.

**Comment by Superbert25** [comment]
I’m new, started with 9.6, now on 9.6b (again).

9.7 beta crashed all the time (within 30 seconds). I flashed over OTA, could that have something to do with it? So, I reverted back to 9.6b over OTA, which is stable enough (few crashes a day). I can dive into the issues after next week.

R.  Eeg.

**Comment by frtz13** [comment]
my report about the 9_7_beta:
I have 2 YC600 inverters, approx. 35 % resp. 50% Zigbee signal strength.
the ESP-ECU ran without problems for 25h, no crash,
resetCounter = 1.
CC2530 zigbee module.
Frontpage looks ok on my phone. I never saw more than 2 decimals.
works fine ! thanks.

**Comment by swbouman** [comment]
@patience4711 , thank you for your response! Your answer is clear to me, the polled data can be a few minutes old and therefor not really accurate. 

About the crashes: the software is stable during night time. During polling time the esp crashes a lot. I’ll try to power the cc2530/2591 direct from a power source. The behavior looks like a power shortage. The 2530 is polling and the esp is sending data over WiFi. That consumes a lot of energy. 

I’ll build the new power source tomorrow and report back to you.

**Comment by patience4711** [comment]
@swbouman  You still didn't answer my question about the frontpage of 9_6b. Since you where mentioning the totals (not present in 6b) I thought maybe you have the wrong version.  If the problem is related to the number of inverters you should be able to find a stable situation by lowering the number of inverters.
If your powersupply is 3A there shouldn't be problems but if not there could be brownouts. 

@Superbert25 What zigbee do you use, by chance the 2530+2591?

**Comment by swbouman** [comment]
@patience4711 at the moment I’m running 9.6b. The program is stable since night mode. 
that’s why my thought are about the power consumption of the wemos and the zigbee unit. 

I’m currently powering the unit with a 2 amps usb adapter. So that could be the problem. I keep you posted. 

Next week the installer will check the inverters on the roof. The polling data gives 11vac on most of the roof inverters. No power is produced. 

Here is my screenshot.

**Comment by joffito** [comment]
Maybe a big cap like 1000uF across the ESP power pins is enough to keep it running. 2 A sounds like enough to me.
How is the DS3L wired up. Each Inverter goes to the grid separately (or via a node) or are they kind of daisy chained / pass through system ?

**Comment by patience4711** [comment]
If an esp can draw 400mA than this is 0.4*5=2A but when a hungry cc2530+2951 is connected . . . . . 
In the building instructions a 3A powersupply is recommended.
To rule out all of the new features, please test with 9_6a, this has been proven to work !!!!!

**Comment by joffito** [comment]
i think it only pulls the 400mA very briefly and also at 3.3V. so with a big cap that could be buffered. but i don't know how much the ZB module pulls. anyhow i am curious if the roor cause can be found. having a decoupling cap certainly does not make things worse, also not with a 3 A device as the peal current may be the culprit

**Comment by Superbert25** [comment]
> 

I am using a cheap CC2530 without amplifier. I ordered a new one with 2592 and external antenna connection.

**Comment by patience4711** [comment]
@joffito  Do you use that big cap yourself? I am sure that you don't need it if you have a good 3A powersupply. 
Could you tell us what version you are running with what hardware/inverter(s) and if there are stability problems?

**Comment by joffito** [comment]
No i don't use it with my simple CC2530 and ESP with only 1 DS3S inverter paired. But it helped in the past with some GSM modules. But you're probably right - a good 3A supply should be sufficient. Let's see how it turns out. I am running the 'original' 9.6. very stable since 11 d. it would also be interesting if people with trouble wired or soldered the zigbee module to the ESP

**Comment by frtz13** [comment]
ESP-ECU v. 9_7_beta up for 3 days. resetCounter = 8.
D1-mini pro board + cc2530 running from a 5V / 1A power supply.

**Comment by patience4711** [comment]
@frtz13  thanks, so the esp stays stable meaning that the new features are not involved. We can see here however that the zigbee crashes some times. This is an old problem that occurred with a high polling frequency (more than once in 5 minutes). In the past the polling frequency was configurable but since it didn't work stable the 5 minutes (same as the official ecu) became standard. Multiple inverters means virtually a higher polling rate and that causes the crashes of the zigbee. The reason is supposedly hidden in the zigbee's software (a buffer overrun?) but the designer is convinced that this is not the case. We know that when this happens very large serial messages are sent. This also could cause the zigbee to crash because the reading of the serial buffer takes too long.  Maybe the wdt overflows because of that. I really don't know, 

So what can I do? I am thinking of some sanity check and buffercleaning in between the polling. Maybe this could help and it certainly won't harm. I will work this out and will come up with a modified version.

**Comment by swbouman** [comment]
Hello all,

After a weekend of testing with a 10 A power supply, just to be sure 😜, and a lot of crashes when switching from the console view to the home view, I installed the new 9.7 version today. 
This latest version gives me a solid online system for 2 hours now. 
I got some error 50 status codes, but after a minute or 10 the system restarts the zigbee module. Mem is around 16000 and stable. 

To avoid the error 50 code, a little delay between polling different inverters could be the(or a) solution.

**Comment by patience4711** [comment]
Oke so now the situation is that the esp is stable but the zigbee still crashes. I am thinking about a method that divides 5 minutes by the number of inverters and uses this result as a pause between pollings of each inverter. You may be right that this could help but i remember that every higher polling rate than 5 minutes leaded to crashes of the zigbee. Nevertheless i'l give it a shot. I'l come back when i have this implemented.

**Comment by swbouman** [comment]
@patience4711 , you’re right about the stablility. Now solid for 3 hours. 

About the zigbee stability, could you pls start with a delay of 2 seconds between polling each inverter, everytime auto polling is started? So the polling is started after 300 secs, with a timeout of 2 secs after an inverter poll is started? In my situation the polling of all inverters will take 14 secs. I think this is a minor code change for your program.

**Comment by patience4711** [comment]
Oke [here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_7xb.bin) it is. With a delay of 2 seconds between each poll. Can you explain why you think that this would make a difference? I hope you are right but wit the story of the high poll rate in mind...

**Comment by swbouman** [comment]
It is a shot in the wild @patience4711. I took the higher polling rate in mind. I’m the console I saw the polled inverters coming in quickly after each other. In mine opinion a new big call can be written to the cc2530 wile it is still processing the previous. So that’s why I think this could be a solution. 

An other thing I think about is the disabled serial debugging from the esp when zigbee is  enabled. I don’t know if the serial debugging from the esp is disabled at that moment or if it is forwarded to the cc2530. That could cause a failure in the cc2530 due to not handled serial commands… that would make a big investigation. 

I’ll test the new firmware tomorrow. Thanks for the big support to this project!

**Comment by swbouman** [comment]
Hello,

I tested the new 9.7 firmware today. Uptime is for about 4 hours, where after the esp reboots. I’ll investigate if something has todo with the WiFi, but I doubt that because all other esp’s are running stable for months. 

Ive not experienced any error 50s anymore. So the break in polling between inverters is an outcome. 

Ive another strange behavior. Two inverters (far away from the esp) have polling issues with code 11 and 15. At the next polling they give data and a signal strength about 30% 

Does anyone has this issue aswell? When auto polling is off, and inverters are polled by sending the poll command over mqtt polling is instant for these two inverters. 

![15C80B60-92FA-4CCE-B074-A7C837730A82](https://user-images.githubusercontent.com/35607233/223490986-a4996472-5ff7-472c-ba5d-580835ce0219.jpeg)

—-

![41C64D5B-CC37-4CAA-8559-57EBAC786369](https://user-images.githubusercontent.com/35607233/223490992-7760c241-fc61-45f5-bfea-1edb24ec043e.jpeg)

**Comment by swbouman** [comment]
![Uploading 92BA67F5-62E6-48C9-A104-7A237C5B1C53.jpeg…]()

**Comment by swbouman** [comment]
![FE6688CB-0FBE-48B5-A37F-FD4C9E48E125](https://user-images.githubusercontent.com/35607233/223491975-7ed3627f-7440-457a-a35d-c61bfd14b859.jpeg)

**Comment by patience4711** [comment]
That ESP crash after some hours,.. weird.  I am still wondering if this has something to do with the number of inverters. The other issues seem to be a range problem to me. 
At this point i wouldn't know what else to do. If the other users share their experiences with this [9_7xb](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_7xb.bin) version here we might find a systematical  reason for the crashes.

**Comment by frtz13** [comment]
installed the 9_7xb version. I'll report back tomorrow.

**Comment by frtz13** [comment]
version 9_7xb up for 11h now, no problems. resetCounter = 0.
on thing I would like to mention: I never stay connected to the ESP-ECU web interface with the browser. I just have a look and close the window afterwards. Especially, the INFO page makes http requests continuously, retrieving the current time.

**Comment by patience4711** [comment]
@swbouman as far as i can see only inverters 0, 3, 6 show a correct polling answer. This is weird because the program checks some properties of the answer and rejects it if it not matches the criteria. 
Did you read [here](https://github.com/patience4711/RPI-APS-inverters/issues/77) that there seems to be a batch of ds3 inverters that have issues?

**Comment by swbouman** [comment]
@patience4711 thank you for looking in the data. As far as I know, inv3 has one panel attached, so I’ll disable the second one in the near future. 

Today the installers are back because of the wrong readings. They discovered that one inverter is probably dead because of bad installation and the others weren’t attached to 220v grid at all. 

This was in the morning and they went shopping for tools since then. 

Hope they will be back today to finish the job. Then all inverters will produce power. 

The company owner was here to apologize for the first group of installers, which worked here.

**Comment by patience4711** [comment]
@swbouman this is a scandal, not much can go wrong with the installation, bunglers! Anyway now there is hope that the ECU can work properly.

**Comment by frtz13** [comment]
@patience4711 I connected to the ESP_ECU with 3 browser windows. navigated with one of these to the INFO page. the ESP-ECU crashed rapidly, as soon as I started to navigate.
while the front page is relatively sparse with HTTP requests (about 1 for each inverter every 10 seconds approx.), the INFO page makes approx. 10 requests per second to get the current time.

**Comment by patience4711** [comment]
@frtz13 Thanks for testing, if i open 4 browserpages (3 on chrome and one on my phone, all to the infopage, no crashes occure. But i don't have traffic on the frontpage so it is not completly comparable. The responsiveness decreases indeed. The refreshrate of the time is about 2 seconds, i can change in such way that the script only runs once at pageload. It is only a check that system time is correct so not really important.
[v9_7xc](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_7xc.bin)

**Comment by frtz13** [comment]
in the 9_7xb version, INFO page, the HTTP request rate for the current time is much greater than every 2 seconds. it is about 10 per second, maybe more. checked with both Firefox and Edge (Chromium).
ok, in the 9_7xc version, these request are gone.
BTW, would be nice to have a /get.rssi request to get the current wifi signal level.

**Comment by patience4711** [comment]
The wifi signal strength is displayed in the infopage. If you refresh the page you'l get the current level.  ( WiFi.RSSI()) )

**Comment by frtz13** [comment]
... I know. the idea is to request is once a minute or so, and display it in my home automation system.

**Comment by patience4711** [comment]
Sorry too less programspace left for "nice to have" additions. In the childhood of this project i had this to monitor the free memory to see if the crashes could be explained with it. Lets concentrate on getting the system stable insteat.

**Comment by frtz13** [comment]
9_7xc version up for 18h. no crash, resetCounter = 0.

**Comment by frtz13** [comment]
9_7xc version up for 48h. no crash. resetCounter = 0, which is significantly less than previous versions. well done, @patience4711 .

**Comment by frtz13** [comment]
9_7xc version: got a reboot this morning, when connecting to the web interface. It looked like the ESP choked when fetching the data for the second inverter. I also got a Zigbee reset this afternoon.

**Comment by patience4711** [comment]
@frtz13  You can see the difficulty here, these incidents don't happen systematically so it's impossible to find out what the cause is. If it is the websever that crashes than it must be the new frontpage causing that. Because to my knowledge this doesn't happen with the former versions. Would be interesting to know how if the 9_6 version works stable in your situation.
But if it is the frontpage why not everytime you visit it?  

As for the zigbee, the cc2530 is seems pretty outdated and its memory is vulnerable for corruption, Zigbee2Mqtt doesn't recomment it for this reason. There is however no alternative that has the right firmware and can be connected to the ESP.  After a lot of experiments i couldn't find a possible reason (could be firmware related) so i made the system invulnerable for these crashes. When it happens, every 10 minutes there is a healthcheck that recoveres the zigbee. In worst case you could miss 2 polls. We'll have to live with it I'm afraid.

**Comment by frtz13** [comment]
>> But if it is the frontpage why not everytime you visit it?
Maybe ist just concurrence of events. display the frontpage while zigbee traffic going on...
I hardly ever display the ESP-ECU web pages. Mostly to check the wifi rssi from time to time (the ESP-ECU is quite far away in the garden). And I did more often recently, to give some feedback about the new version.
the 9_6 version had been running for months without problems. just a Zigbee reset from time to time.

**Comment by patience4711** [comment]
@frtz13 So it must be the new frontpage then. Requesting data from all inverters at the same time may be too much for the server. Could even be that the mosquitto network activities cause it. I don't know, the system has an async webserver that runs its business in the background. It is very hard to debug.

So for you the new frontpage is not very important an the old version is goed enough?

I was wondering: Sometimes it seems that something is stacking up in the zigbeemodule, that would explain why the more polls id does, the sooner it crashes. If we would force a reset of the ZBmodude every midnight, than its memory is cleared and maybe is wouldn't crash during the day. So i compiled [v9_7xd](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_7xd.bin) with this idea implemented.

**Comment by patience4711** [comment]
@frtz13  Yes i forgot that, sorry. Could you download and install it again [v9_7xd](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_7xd.bin) , i made another minor change to the significance of the resetcounter, These forced resets do not increase the resetcounter, only the incidental resets are counted. So you could see in the log that the reset took place but the resetcounter is still 0 (hopefully).

**Comment by frtz13** [comment]
@patience4711 ok, done.

**Comment by frtz13** [comment]
v.9_7xd. uptime: 2 days. resetCounter=1.

**Comment by frtz13** [comment]
v9_7xd. uptime: 4 days 4hrs, resetCounter=2
@patience4711 I'd like to ask another time for an option to get the "retained" flag set on MQTT messages.
in the case of a restart of the system consuming the MQTT messages, with the "retained" flag not set, it would start with an "unknown" state for the energy production (until the next MQTT messages is posted). If precautions are not built into the formula, a transformation of Wh to kWh would result in a zero production value. A "total_increasing" energy sensor will handle this as a "reset".
This scenario could be avoided by having the MQTT messages posted with the "retained" flag set. In this case, after a restart, the consuming system will get back the latest value immediately.
As far as Home Assistant is concerned: such a restart happens every time you add/modify an MQTT sensor, and re-load the MQTT sensor definitions.
If adding UI elements is an issue, this could be handled by special Dom.Idx values (>= 10, for ex.)

**Comment by swbouman** [comment]
Hi There,

I'm on 9.7XD since a few minutes. The install company is working on the inverters and panels. I'll report back in a day about the uptime of the program. The previous version is working fine, when the webinterface is not touched. 

We keep in touch

**Comment by frtz13** [comment]
v9_7xd. uptime 6 d 16h . resetCounter = 3.

**Comment by patience4711** [comment]
@frtz13  Oke that looks stable enough to me. The resets do not bother? 
About the retain flag, i can't use the idx to decide that.  If i make that optional it is complicating the program too much. What if i would give the formats 3 and 4 standard the retain flag. Could that bother other users? I can't see any adverse effects, what do you think?

**Comment by frtz13** [comment]
@patience4711 right now we are at nearly 9 days uptime and resetCounter=4. Such infrequent resets do not bother me.
about the "retained" flag: I do not see any adverse effects, either.

**Comment by frtz13** [comment]
@swbouman the "retained" flag only changes what happens when a consumer freshly connects to the MQTT broker. when - for a topic - a message has been posted with the "retained" flag, he'll get this message. otherwise, he has to wait for the next message which will be posted for the topic.
you decide in the configuration, what happens when no more MQTT data is received (expire_after parameter in the sensor configuration). for power, voltage, current, temperature values I find it useful to let these sensors expire after a bit more than 5 minutes.

**Comment by patience4711** [comment]
@frtz13  [here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_7xe.bin) is a version with the retainflag set  for mqtt formats 3 and 4.

@swbouman the retain flag retains the last message until its overwritten, so any new subscriber gets always the last message instantly. This doesn't affect anything else, only a new subscriber would know it. 
If i remember well, someone else was able to compile (look at the issues). I still don't know if the new frontpage causes the reboots, you could shine a light on that by testing with the old 9_7 version. 
The ESP is running an asynchonous webserver that is very hard to debug but i suspect that it could crash when the data of all inverters at once is retrieved by a client.

**Comment by patience4711** [comment]
I ported this software to an ESP32, please see the relevant issue. That was no joke, a hell of a job. I hope that there are people willing to test it.  Should be more stable due to the larger memory.

**Comment by swbouman** [comment]
I’m in! I tried the latest 9.7 test and seeing drop mem live. The 8211 was up for just 10 secs and then not responding. I’ll install the new version on a esp32, tough this esp is way too Powerfull for this purpose I think. The esp32 has capabilities to run a lot of sensors. 

But if it helps to get the program stable I’m in!

**Comment by Aikonnnn** [comment]
Awesome, i'll order one if your results looks promising @swbouman

**Comment by patience4711** [comment]
There is some news, thanks to the contribution of a friendly user we may have found a solution for the zigbeecrashes.
This involves a simplified construction of the poll command, with less memory footprint and maybe less risk of memory corruption. You can donwload this [v9_7g](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_7g.bin).

**Comment by Superbert25** [comment]
I will give this latest version a try today.

I changed my HW to a CC2530 + CC2591 now; range / signal quality is better now. The attempt to use a CC2530+CC2592 failed...probably due to faulty HW.

**Comment by Superbert25** [comment]
First impression: Stable, immediate connectivity to all inverters at boot-up

**Comment by frtz13** [comment]
installed v9_7g. working fine here so far. thanks!

**Comment by frtz13** [comment]
v9_7g: I get a Zigbee reset in the log every 10 minutes now. MQTT data is sent every 5min and looks ok.
```
1-16:16:22	mqtt	connected
1-16:16:19	zigbee	ZB coordinator started
1-16:16:8	zigbee	ZBmodule hard reset
1-16:16:7	zigbee	zb down, received :
1-16:6:19	zigbee	ZB coordinator started
1-16:6:8	zigbee	ZBmodule hard reset
1-16:6:7	zigbee	zb down, received :
1-15:56:22	mqtt	connected
1-15:56:19	zigbee	ZB coordinator started
1-15:56:8	zigbee	ZBmodule hard reset
1-15:56:7	zigbee	zb down, received :
1-15:46:22	mqtt	connected
1-15:46:19	zigbee	ZB coordinator started
1-15:46:8	zigbee	ZBmodule hard reset
1-15:46:7	zigbee	zb down, received :
1-15:36:19	zigbee	ZB coordinator started
1-15:36:8	zigbee	ZBmodule hard reset
1-15:36:7	zigbee	zb down, received :
1-15:26:22	mqtt	connected
1-15:26:19	zigbee	ZB coordinator started
```

**Comment by swbouman** [comment]
I've an uptime of 2hrs and 13 min, free mem down from 18000 to 12000. Same zigbee behavior as described above; 13 resets in 2 hrs.

**Comment by Superbert25** [comment]
Same here. Every 10 minutes a Zigbee hard reset.

**Comment by patience4712** [comment]
I must have fouled the health check process that runs every 10 minutes when I worked on the esp32 software. I'l look into this tomorrow.

**Comment by frtz13** [comment]
beware of the v9_7i version! it loses wifi and inverter information.
on v9_7i: after having re-configured the wifi network: no inverter found in the configuration. I paired the 1st inverter. worked fine. I tried to add the second inverter. The ESP-ECU restarted and again had lost its wifi configuration. Even after configuring it again, I could not get it connect to my network. I pressed the "Erase files" button. Then I could reconnect to my network.
Then I returned to the v9_7g which magically and automatically recovered the "old" wifi and inverter information.

**Comment by patience4711** [comment]
Oh, i compiled that with other memory settings, so the file sytem doesn't work properly anymore.  It didn't bother me because i flashed it on a new device. I recompiled with the original setings

**Comment by frtz13** [comment]
... ok, v9_7j definitively looks better. thanks!

**Comment by swbouman** [comment]
Could it be an option to build in a polling check. If polling of a inverter fail, retry polling that inverter. if the second poll fails, do a health check and restart the polling sequence?

I have two inverters mounted on a longer distance. Sometimes polling fails, but after a second try the polling of the inverter succeeds.

I dont have anby zigbee crashes anymore after installing the G version. Hence the frem mem is 13000 bytes after 2 days uptime. I still believe som mem is beeing held by the program (webinterface pages).

And still the ecu is rebooting after closing the console page by pressing done. Hope you could look into that.

**Comment by patience4711** [comment]
@swbouman sorry but that debug check would even more stress the memory. When a poll failed it can succeed the next time so no harm done. 
As to your problem with the console, i can't reproduce that but that's also behaviour of the webserver which i can't debug. I am working with the log and console open simultaneously and have no problems, I guess the esp32 project is the way to go for you.

**Comment by swbouman** [comment]
@patience4711 thanks for the answer. Even with 0 or 1 inverter the esp is rebooting after pressing done in the console page. No mem dumps or anything. I think its hard coded in the software. 

At the moment i'm pairing the inverters again due to the unstable I version. After a clean install it worked great. I'm at J for now, keep you posted.

**Comment by patience4711** [comment]
@then i would (and all others) have that too....

I couldn't resist to include one of the novelties from the esp32 project. In this version the frontpage has links to the details of an inverter. For me this works good. [v9_8_expa](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_8_expa.bin)

**Comment by frtz13** [comment]
@patience4711 v9_7j up for 10 hours. resetCounter=0. free memory 19656 bytes: about 1kB more than previous versions.
My ESP-ECU never crashed when closing the console page.

**Comment by patience4711** [comment]
I want to thank everbody who contributed to development of this new version. I am still interested in the experiences of users, please mention how many inverters you have.
**** preliminary conclusion ****
Based on the reactions here i think we could say that the new webinterface works oke. The Users with more than 5 inverters have stability problems that i cannot reproduce and/or solve. These problems are most likely related to the lack of sufficient memory in the ESP. The webserver eats too much memory whereas the memory itself is stressed by the large number of variables it should remember. I am afraid that they will have to go for the ESP32 project.

**Comment by frtz13** [comment]
installed v9_8. it remembered wifi data and inverters ;-)
2 x YC600

**Comment by joep2000** [comment]
Hi!
Nice work @patience4711
Now running v9_8 for 1 hour now, with zero restarts. I've 7x DS3 paired.

Looking forward to the ESP32-S2 next week to experiment with. Is the S2 compatible with your ESP32 version?

**Comment by patience4711** [comment]
@joep2000  That's for you to find out, i don't own one, It seems that it is possible to use pin 16 and 17 as serial2 so i think it could work.

**Comment by frtz13** [comment]
v9_8 up nearly 48h. resetCounter=0. free memory 18160 B.
2 x YC600

**Comment by frtz13** [comment]
v9_8 up 5 days. resetCounter=0. free memory 17424 bytes.

**Comment by swbouman** [comment]
Hi @patience4711 ,

I can see the program freeing mem. On version 9.7 the mem is fluctuating between 18800 and 14270. 

After all most 4 days, the info page was displayed as unreadable code. Homepage was still readable. 

Then the esp rebooted. I’ll update to 9.8 tomorrow with a fresh D1 mini. Hope it will help to get the system more stable.

**Comment by frtz13** [comment]
@patience4711 I have the impression that free memory goes down a little bit every time I have a look at the front page, which I do sometimes, though not frequently. I mostly use a URL going directly to the INFO page. Free memory is currently at 16880 bytes. successive displays of the INFO page may result in slightly different values. I'll have a look tomorrow if the value went up again.
If we got an MQTT packet with some system info from time to time, this would be easier to trace... ;-)

**Comment by patience4711** [comment]
Oke, this experimental version sends  **{"idx":123,"nvalue":0,"svalue":"12345"}** to the sendTopic, at every healthcheck. 
If the sendtopic has a trailing slash then it will be sendtopic/heap. 
Provided that you enabled mqtt.
The idx can be changed in console 10;DOMDIX=xxx, this is a sensor id for the Domoticz system. 
The svalue is the free heap.
You can download it [here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_8_mqttlog.bin)

**Comment by joffito** [comment]
i flashed the 9_8 today. i noticed that the values on the front page do not match the values (totals) for the detailed view. i only have 1 inverter.

![Screenshot_20230413_134717_Firefox](https://user-images.githubusercontent.com/114950821/231750651-b27c21ee-a6fc-4476-abcb-a3d8b39a2983.jpg)
![Screenshot_20230413_134721_Firefox](https://user-images.githubusercontent.com/114950821/231750676-911ec94e-5c16-4d92-8448-bf503a2afd63.jpg)

i opened the info page like 20 times and closed it rapidly. free memory went down and up with a tendency to go down. after like 20 times the esp crashed.
for my understanding  it would be a better option to leave out help pages on the webserver (that can go to the wiki) and use the program space to make the html files compliant with the html standard (like all necessary closing tags).

**Comment by patience4711** [comment]
@joffito Could you point out which values should match?
Maybe you should try this one [v9_8_expb](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_8_expb.bin)
I improved the html a bit, omitted some strings and used the F macro which yields some more free heap. No mater what i try with 2 infopages open and rapidly refreshing (total 5 pages open) to crash the ESP with 5 pages open, it keeps up. Can't see the heap going down.
Would be nice to know where the necessary closing tags fail. In the details page i added the </html> already.

**Comment by joffito** [comment]
![Screenshot_20230413_161244_Firefox](https://user-images.githubusercontent.com/114950821/231786992-c36d3643-ac1a-4d10-84cb-dc6416ca05a6.jpg)
![Screenshot_20230413_161250_Firefox](https://user-images.githubusercontent.com/114950821/231787005-064bcf15-a787-41ca-949d-017ce4dc8b42.jpg)


The W on the front page says fir example 55W for panel 1. Now if i open the inverter 0, the detail page says: 36,4 V and 1,4 A fir panel 1 which is about 51 W.

i think one has to close the info page and open it up again,nit just reload. but i somehow doubt that the missing html is the culprit. but still it's very good that you implemented the changes. will flash the exp. v 9_8 soon and test.i'll search the source of the infopage for a potential issue then as well but i am no programmer as well.

but i like the new detailed inverter page :-)!

**Comment by patience4711** [comment]
@joffito maybe it was, i made some changes to that too. That page was a large string which could influence the memory, however i myself never saw that. I noticed that sometimes the menu page was not loading which triggered me to make these changes. 
About the values, read [here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/wiki/5-POLLING#values) in the wiki.
In short; Power is an average over 5 minutes, calculated from the energy generated in that time.  dcV and dccC are snapshots.

**Comment by patience4711** [comment]
I am closing this issue because most of the posts are not relevant anymore and the readability becomes poor becaus of the length.
We will continue with a new issue "new version v9_8b"
Thanks again verybody, for all the input.
