### ISSUE TITLE
Memory leak 9.7 exp

### ISSUE THREAD

**Issue by swbouman** [patience4711/read-APSystems-YC600-QS1-DS3#91]
Hi there. Since today I’m testing this magnificent program. I faced a lot of reboots and pairing today. 

Now it’s dark, I can see the free memory is leaking. Every second a few bytes disappear from the available free mem. No inverters are polling at the moment. 

Anyone facing this problem?

**Comment by frtz13** [comment]
seems to be stable here. 2 inverters paired. 18344 bytes free. I'll watch tomorrow during active polling.

**Comment by patience4711** [comment]
That is a nasty problem which i cannot reproduce. The major difference betweeen the stable 9_6 and 9_7 is that a complex script is running on the frontpage. The more inverters, the longer this script runs. But this all happens at client-side so i don't believe that this could be the cause. 
Could be that the watchdog timer overflows. If you connect the esp to a serial monitor you should be able to see the reason for a reset. 

If your system is running oke with version 9_6 than i know that the webpage is to be suspected. I recompiled 9_6 [ESP-ECU-9_6b.bin](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/ESP-ECU_v9_6b.bin) with the feature for the topics per inverter.
Did you check all your settings,  no weird values somewhere?

**Comment by swbouman** [comment]
I'm now on the 9.6b version. I have to look tomorrow if the esp reboots frequently. Today I noticed a nr 50 error. I suspect this is due to the 7 inverters to be polled, which is probably too much for the system.Is it possible to make a short delay between polling different inverters? When I poll manually it runs fine. 
Sometimes a poll fails with a error 7 or 17. When I poll again the poll runs fine. 
probably a future request to repoll if no data is returned.

The mqtt topic option is really a good option for the program, it makes it a lot better to enclose in other home servers.

Side notice; I have serious problems with 50% of the inverters. No ACV is reported. Temperature is reported correct. There are spikes in power output. I called the installer to review the system. (polling is working and signq is between 7 and 23 %)

**Comment by patience4711** [comment]
I don't think its the number of inverters but that easy to find out. If you start with 3 inverters (we know that that works) you can scale up to the number where the problems begin. Maybe you can identify certain inverters where it goes wrong.

So you are saying that when you disable autopolling an poll manual (via console?) there are no (at all) stability problems?

**Comment by swbouman** [comment]
@patience4711 I could reproduce the problem by entering polling commands to the console. After 10 commands or so, the system is booting. The program is shutting down the serial log when zitbeen is online. But I managed to catch the exception :)

`[23:27:29] ets Jan  8 2013,rst cause:4, boot mode:(3,0)
[23:27:29]
[23:27:29]wdt reset
[23:27:29]load 0x4010f000, len 3456, room 16 
[23:27:29]tail 0
[23:27:29]chksum 0x84
[23:27:29]csum 0x84
[23:27:29]va5432625`

**Comment by patience4711** [comment]
Oke, so its a wdt reset as i suspected. Is this happening every time you leave the console? This could not have anything to do with the number of inverters I think. But in my case this never happens.  So why do you have this and many others, like me, do not ? Strange....
Are you sure that the esp was completely erased before you installed the software?
