### ISSUE TITLE
Coordinator won't start

### ISSUE THREAD

**Issue by JanMueller207** [patience4711/read-APSystems-YC600-QS1-DS3#98]
Hello everyone,

and first of all thank you for sharing this project, good work!
Anyway, I tried to pair my AP DS3-S to the Node MCU with Zigbee Module and after some trials the inverter was successfully paired and is listed in the overview. But it is not displaying any value (just n/a) and it always displays "Initializing the Zigbee Radio..." in the first tab.

The communication between NodeMCU and Zigbee seems to work fine, I tested it according to "To test the zigbee hardware you can type "10;ZBT=2710AABBCC" in the console. You should get inMessage: FE036710AABBCCA9"

![APSystems_ECU](https://user-images.githubusercontent.com/28809487/229298021-4dad8fb8-f1a4-4ca0-887a-39168d5d16b1.png)

Any Ideas well appreciated, thanks in advance. :-)

**Comment by joffito** [comment]
Can you do a health check of the zigbee via the console?

**Comment by joffito** [comment]
10;health

**Comment by JanMueller207** [comment]
Thank you for the Quick reply, here are 2 answers from the Console:
I thought the connection is okay due to the answer...
![IMG-20230402-WA0006](https://user-images.githubusercontent.com/28809487/229376031-ba1124a2-cf3d-47ad-bec4-4c5ed2363c53.jpg)
![IMG-20230402-WA0005](https://user-images.githubusercontent.com/28809487/229376032-e0d3501c-acdf-4078-9789-9d7cec7ff50d.jpg)

**Comment by joffito** [comment]
which zigbee module and firmware are you using?

**Comment by joffito** [comment]
Did you erase the chip prior to flashing? i think somebody reported that he had to flash several times before it worked. maybe also just try the .bin file. 
otherwise i don't know what could be the cause. i used esptools under linux and it worked well but i had to erase the flash first. 
also double check the wiring to the esp ;-)

**Comment by patience4711** [comment]
To me it seems that the wiring is oke, the loopbacktest works. The coordinator doesn't get up. What version of the ESP-ECU did you install?

**Comment by JanMueller207** [comment]
> Did you erase the chip prior to flashing? i think somebody reported that he had to flash several times before it worked. maybe also just try the .bin file. 
> otherwise i don't know what could be the cause. i used esptools under linux and it worked well but i had to erase the flash first. 
> also double check the wiring to the esp ;-)

I did not erase the Chip. Will try it out next time, is there an Option with CCLoader?
Can I find the final bin file for CCLoader somewhere in the folder? Would like to make Sure, that the compilation was fine.

**Comment by JanMueller207** [comment]
> To me it seems that the wiring is oke, the loopbacktest works so the serial communication is oke. The coordinator doesn't get up, thats the real problem here. 
> Could be the reset wire, wrong firmware or ... since you seem to have a self compiled version of the ESP ECU....?

I uploaded the ESP ECU file from your folder from Arduino and Compiled it there. So it should be the original one or where are your doubts coming from?
Thank you!

**Comment by joffito** [comment]
> > Did you erase the chip prior to flashing? i think somebody reported that he had to flash several times before it worked. maybe also just try the .bin file.
> > otherwise i don't know what could be the cause. i used esptools under linux and it worked well but i had to erase the flash first.
> > also double check the wiring to the esp ;-)
> 
> I did not erase the Chip. Will try it out next time, is there an Option with CCLoader? Can I find the final bin file for CCLoader somewhere in the folder? Would like to make Sure, that the compilation was fine.

I never used CCLoader, sorry. I used a Raspberry Pi and this tutorial: https://blog.boris-wach.de/permalink/265. I think i just had to get WiringPi from another source.

1. Erase the ZigBee Flash
2. Flash directly the Hex-File provided (no need for any recompilations)

And just to try it out: flash the .bin file for the ESP directly which is provided like 9_6c. No own compiling.

OR: your ZigBee module is faulty...

**Comment by patience4711** [comment]
@JanMueller207 I never saw any german laguage in my console so i thought you must have your own compilation of ESP-ECU.

**Comment by JanMueller207** [comment]
> > > Did you erase the chip prior to flashing? i think somebody reported that he had to flash several times before it worked. maybe also just try the .bin file.
> > > otherwise i don't know what could be the cause. i used esptools under linux and it worked well but i had to erase the flash first.
> > > also double check the wiring to the esp ;-)
> > 
> > I did not erase the Chip. Will try it out next time, is there an Option with CCLoader? Can I find the final bin file for CCLoader somewhere in the folder? Would like to make Sure, that the compilation was fine.
> 
> I never used CCLoader, sorry. I used a Raspberry Pi and this tutorial: https://blog.boris-wach.de/permalink/265. I think i just had to get WiringPi from another source.
> 
> 1. Erase the ZigBee Flash
> 2. Flash directly the Hex-File provided (no need for any recompilations)
> 
> And just to try it out: flash the .bin file for the ESP directly which is provided like 9_6c. No own compiling.
> 
> OR: your ZigBee module is faulty...
> 

Thank you, will try that next time. On the first view I did not find the provided hex file in the files here, Could you pls tell me where exactly!?

**Comment by JanMueller207** [comment]
Hello Patience 4711,

I uploaded the newest FW to the ESP and now the Coordinator seems so start:
<img width="536" alt="image" src="https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/assets/28809487/305db8a7-3caa-40ad-9e1d-35caafc0b5a6">

The inverter is not here so I cannot test the pairing but it seems to work so far in between the ESP ECU <-> Zigbee module!?
